version: "3.9"

services:
  
  server:
    container_name: prakticum_server_container

    image: ghcr.io/bondloong/teamwork_01_project/server:32efbf399a06fcc8cfd8d56bebd6230cdd85553b
      
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        API_SERVER_PORT: 3001
      
    restart: always
      
    ports:
      - "3001:3001"

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/mongo_game_db --quiet

    environment:
      API_SERVER_PORT: 3001
      DATABASE_URL: mongodb+srv://admin:parol1@spaseship.whiq1c1.mongodb.net/spaseship?retryWrites=true&w=majority&appName=spaseship

    env_file:
      - ./.env

  client:
    container_name: prakticum_client_container

    image: ghcr.io/bondloong/teamwork_01_project/client:32efbf399a06fcc8cfd8d56bebd6230cdd85553b

    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: 3000
      
    restart: always

    ports:
      - "3000:3000"

    environment:
      CLIENT_PORT: 3000
      API_SERVER_HOST: http://localhost
      API_SERVER_PORT: 3001

    depends_on:
      - server
