# Важно: при запуске docker-compose надо указать файл с env-переменными, например, файл с тестовыми значениями .env.sample (реальные данные в репозитории не храним)
# docker-compose --env-file .env.sample up
# если рядом с docker-compose.yaml лежит файл .env, то docker-compose будет использовать его по-умолчанию

# версия синтаксиса
version: "3.9"

# Описываем образы, каждый из которых соответствует отдельному приложению (база данных, server и client)
services:
##############################################################################

  # Образ для серверного приложения (которое общается с БД и предоставляет апи форума, темы и пр.)
  server:
    # Имя контейнера после того, как контейнер будет запущен
    container_name: prakticum_server_container

    # Задаем имя создаваемого образа
    # image: ghcr.io/bondloong/teamwork_01_project/server:6dc17c1f9c74a0b7e2df368c5d18823c48d9a344

    # Как будем создавать контейнер? Какой Dockerfile использовать?
    build:
      # Dockerfile берем из текущей папки
      context: .
      # Имя докер-файла
      dockerfile: Dockerfile.server
      # Аргументы, которые будут переданы в процесс сборки образа
      args:
        API_SERVER_PORT: 3001

    # Всегда перезапускать контейнер, когда он останавливается
    restart: always

    # Связываем порт приложения на хост-машине с портом приложения внутри контейнера
    ports:
      - "3001:3001"

    # env-переменные, которые будут доступны внутри контейнера
    # При необходимости, внутрь контейнера можно передать env-переменные, содержащий данные для подключения к БД. В текущей реализации, вся необходимая информация содержится в DATABASE_URL
    environment:
      API_SERVER_PORT: 3001
      DATABASE_URL: mongodb+srv://admin:parol1@spaseship.whiq1c1.mongodb.net/spaseship?retryWrites=true&w=majority&appName=spaseship


    # На всякий случай дополнительно явно указали env-переменные
    env_file:
      - ./.env

##############################################################################

  # Образ для клиентского приложения (которое раздает статику)
  client:
    # Имя контейнера после того, как контейнер будет запущен
    container_name: prakticum_client_container

    # Задаем имя создаваемого образа
    # image: ghcr.io/bondloong/teamwork_01_project/client:6dc17c1f9c74a0b7e2df368c5d18823c48d9a344

    # Как будем создавать контейнер? Какой Dockerfile использовать?
    build:
      # Dockerfile берем из текущей папки
      context: .
      # Имя докер-файла
      dockerfile: Dockerfile.client
      # Аргументы, которые будут переданы в процесс сборки образа
      args:
        CLIENT_PORT: 3000

    # Всегда перезапускать контейнер, когда он останавливается
    restart: always

    # Связываем порт приложения на хост-машине с портом приложения внутри контейнера
    ports:
      - "3000:3000"

    # env-переменные, которые будут доступны внутри контейнера
    environment:
      CLIENT_PORT: 3000
      API_SERVER_HOST: http://localhost
      API_SERVER_PORT: 3001

    # Запускать контейнер после запуска контейнера server
    depends_on:
      - server

##############################################################################

  # Образ nginx https://hub.docker.com/_/nginx
  nginx:
    # Здесь именно image, потому что мы его сами не пишем, он будет взят с докерхаба
    image: nginx

    # Имя контейнера. Можно не задавать
    container_name: nginx_container

    # Всегда перезапускать контейнер, когда он останавливается
    restart: always

    # Эти переменные будут проброшены внутрь контейнера mongo и из них будут браться указаные значения для создаваемой БД
    # Т.к. nginx, SSR-сервер, АПИ-сервер и БД будут запущены в докере на одном сервере, для проксирования запросов nginx будет обращаться по имени контейнера и порту
    environment:
      CLIENT_CONTAINER: prakticum_client_container
      CLIENT_PORT: 3000
      API_SERVER_CONTAINER: prakticum_server_container
      API_SERVER_PORT: 3001

    # Связываем файлы хоста с контейнером
    # nginx.conf из текущего каталога хоста должен быть смонтирован в качестве файла /etc/nginx/nginx.conf в контейнере Docker
    # ключи от ssl хранятся в текущем каталоге на хосте в папке certs и должны быть смонтирован в качестве файла /etc/nginx/certs в контейнере Docker
    # ro - read only
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

    # Проброс порта — на какой порт хоста какой порт контейнера
    # Свзяваем порты, которые nginx слушает внутри контейнера с внешними портами
    # Традиционно, порт 80 для подключений по http и 443 для https
    ports:
      - '80:80'
      - '443:443'

    depends_on:
      - server
      - client
